[package]
name = "solasta-save-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = "1.1.2"
rust-utils = { git = "https://github.com/SoxPopuli/rust-utils.git", tag = "v1.8.0", features = [
    "byte_readers",
] }
